// <auto-generated />
using System;
using DACS_web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DACS_web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250508021922_v10")]
    partial class v10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DACS_web.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MaBenhNhan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DACS_web.Models.BenhNhan", b =>
                {
                    b.Property<string>("MaBenhNhan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BHYT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DanToc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoiTuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgheNghiep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuocTich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TienSuBenhBanThan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TienSuBenhGiaDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TienSuDiUng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBenhNhan");

                    b.ToTable("BenhNhans");
                });

            modelBuilder.Entity("DACS_web.Models.ChanDoan", b =>
                {
                    b.Property<string>("MaChanDoan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoaiChanDoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHoSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaICD")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChanDoan");

                    b.HasIndex("MaHoSo");

                    b.HasIndex("MaICD");

                    b.ToTable("ChanDoans");
                });

            modelBuilder.Entity("DACS_web.Models.ChiTietDonThuoc", b =>
                {
                    b.Property<string>("MaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaThuoc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LieuDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("ThoiGianDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDon", "MaThuoc");

                    b.HasIndex("MaThuoc");

                    b.ToTable("ChiTietDonThuocs");
                });

            modelBuilder.Entity("DACS_web.Models.CuocHenKham", b =>
                {
                    b.Property<string>("MaCuocHen")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaBacSiDuKien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaBenhNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayGioHen")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiHen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCuocHen");

                    b.HasIndex("MaBacSiDuKien");

                    b.HasIndex("MaBenhNhan");

                    b.ToTable("CuocHenKhams");
                });

            modelBuilder.Entity("DACS_web.Models.DanhMucICD", b =>
                {
                    b.Property<string>("MaICD")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenBenh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaICD");

                    b.ToTable("DanhMucICDs");
                });

            modelBuilder.Entity("DACS_web.Models.DonThuoc", b =>
                {
                    b.Property<string>("MaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BacSiKeDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HuongDanSuDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHoSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayKe")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaDon");

                    b.HasIndex("BacSiKeDon");

                    b.HasIndex("MaHoSo");

                    b.ToTable("DonThuocs");
                });

            modelBuilder.Entity("DACS_web.Models.DotKham", b =>
                {
                    b.Property<string>("MaDotKham")
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeSpan?>("GioRaVien")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioVaoVien")
                        .HasColumnType("time");

                    b.Property<string>("HinhThucTiepNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDoVaoVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaBenhNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaCuocHen")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKhoaRaVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKhoaTiepNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgayRaVien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoVien")
                        .HasColumnType("datetime2");

                    b.Property<int>("TongSoNgayDieuTri")
                        .HasColumnType("int");

                    b.HasKey("MaDotKham");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaCuocHen");

                    b.HasIndex("MaKhoaRaVien");

                    b.HasIndex("MaKhoaTiepNhan");

                    b.ToTable("DotKhams");
                });

            modelBuilder.Entity("DACS_web.Models.HinhAnhYTe", b =>
                {
                    b.Property<string>("MaAnh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiHinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHoSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaAnh");

                    b.HasIndex("MaHoSo");

                    b.ToTable("HinhAnhYTes");
                });

            modelBuilder.Entity("DACS_web.Models.HoSoBenhAn", b =>
                {
                    b.Property<string>("MaHoSo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChanDoanRaVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KetQuaRaVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaBacSiDieuTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaBacSiLapBenhAn")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaBenhNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TienLuongGan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TienLuongXa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiRaVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHoSo");

                    b.HasIndex("MaBacSiDieuTri");

                    b.HasIndex("MaBacSiLapBenhAn");

                    b.HasIndex("MaBenhNhan");

                    b.ToTable("HoSoBenhAns");
                });

            modelBuilder.Entity("DACS_web.Models.KetQuaKhamMat", b =>
                {
                    b.Property<string>("MaKQ")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaHoSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTaBoPhanMat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("NhanAp")
                        .HasColumnType("real");

                    b.Property<string>("ThiLucCoKinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThiLucKhongKinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TongTrangMat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTriMat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKQ");

                    b.HasIndex("MaHoSo");

                    b.ToTable("KetQuaKhamMats");
                });

            modelBuilder.Entity("DACS_web.Models.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoas");
                });

            modelBuilder.Entity("DACS_web.Models.NhanVienYTe", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaKhoa");

                    b.ToTable("NhanVienYTes");
                });

            modelBuilder.Entity("DACS_web.Models.PhuongPhapDieuTri", b =>
                {
                    b.Property<string>("MaPhuongPhap")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaHoSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTaChiTiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgoaiKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhuongPhap");

                    b.HasIndex("MaHoSo");

                    b.ToTable("PhuongPhapDieuTris");
                });

            modelBuilder.Entity("DACS_web.Models.Thuoc", b =>
                {
                    b.Property<string>("MaThuoc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChiDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TacDungPhu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TuongTacThuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaThuoc");

                    b.ToTable("Thuocs");
                });

            modelBuilder.Entity("DACS_web.Models.XetNghiemCLS", b =>
                {
                    b.Property<string>("MaXetNghiem")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KetQua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiXetNghiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHoSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThucHien")
                        .HasColumnType("datetime2");

                    b.HasKey("MaXetNghiem");

                    b.HasIndex("MaHoSo");

                    b.ToTable("XetNghiemCLSs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DACS_web.Models.ApplicationUser", b =>
                {
                    b.HasOne("DACS_web.Models.BenhNhan", "BenhNhan")
                        .WithMany()
                        .HasForeignKey("MaBenhNhan");

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("DACS_web.Models.ChanDoan", b =>
                {
                    b.HasOne("DACS_web.Models.HoSoBenhAn", "HoSoBenhAn")
                        .WithMany("ChanDoans")
                        .HasForeignKey("MaHoSo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DACS_web.Models.DanhMucICD", "DanhMucICD")
                        .WithMany()
                        .HasForeignKey("MaICD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucICD");

                    b.Navigation("HoSoBenhAn");
                });

            modelBuilder.Entity("DACS_web.Models.ChiTietDonThuoc", b =>
                {
                    b.HasOne("DACS_web.Models.DonThuoc", "DonThuoc")
                        .WithMany("ChiTietDonThuocs")
                        .HasForeignKey("MaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DACS_web.Models.Thuoc", "Thuoc")
                        .WithMany()
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonThuoc");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("DACS_web.Models.CuocHenKham", b =>
                {
                    b.HasOne("DACS_web.Models.NhanVienYTe", "BacSiDuKien")
                        .WithMany()
                        .HasForeignKey("MaBacSiDuKien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DACS_web.Models.BenhNhan", "BenhNhan")
                        .WithMany("CuocHenKhams")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacSiDuKien");

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("DACS_web.Models.DonThuoc", b =>
                {
                    b.HasOne("DACS_web.Models.NhanVienYTe", "NhanVienYTe")
                        .WithMany()
                        .HasForeignKey("BacSiKeDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DACS_web.Models.HoSoBenhAn", "HoSoBenhAn")
                        .WithMany()
                        .HasForeignKey("MaHoSo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoBenhAn");

                    b.Navigation("NhanVienYTe");
                });

            modelBuilder.Entity("DACS_web.Models.DotKham", b =>
                {
                    b.HasOne("DACS_web.Models.BenhNhan", "BenhNhan")
                        .WithMany("DotKhams")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DACS_web.Models.CuocHenKham", "CuocHenKham")
                        .WithMany("DotKhams")
                        .HasForeignKey("MaCuocHen");

                    b.HasOne("DACS_web.Models.Khoa", "KhoaRaVien")
                        .WithMany()
                        .HasForeignKey("MaKhoaRaVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DACS_web.Models.Khoa", "KhoaTiepNhan")
                        .WithMany()
                        .HasForeignKey("MaKhoaTiepNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BenhNhan");

                    b.Navigation("CuocHenKham");

                    b.Navigation("KhoaRaVien");

                    b.Navigation("KhoaTiepNhan");
                });

            modelBuilder.Entity("DACS_web.Models.HinhAnhYTe", b =>
                {
                    b.HasOne("DACS_web.Models.HoSoBenhAn", "HoSoBenhAn")
                        .WithMany("HinhAnhYTes")
                        .HasForeignKey("MaHoSo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoBenhAn");
                });

            modelBuilder.Entity("DACS_web.Models.HoSoBenhAn", b =>
                {
                    b.HasOne("DACS_web.Models.NhanVienYTe", "BacSiDieuTri")
                        .WithMany()
                        .HasForeignKey("MaBacSiDieuTri")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DACS_web.Models.NhanVienYTe", "BacSiLapBenhAn")
                        .WithMany()
                        .HasForeignKey("MaBacSiLapBenhAn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DACS_web.Models.BenhNhan", "BenhNhan")
                        .WithMany("HoSoBenhAns")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacSiDieuTri");

                    b.Navigation("BacSiLapBenhAn");

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("DACS_web.Models.KetQuaKhamMat", b =>
                {
                    b.HasOne("DACS_web.Models.HoSoBenhAn", "HoSoBenhAn")
                        .WithMany("KetQuaKhamMats")
                        .HasForeignKey("MaHoSo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoBenhAn");
                });

            modelBuilder.Entity("DACS_web.Models.NhanVienYTe", b =>
                {
                    b.HasOne("DACS_web.Models.Khoa", "Khoa")
                        .WithMany("NhanVienYTes")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("DACS_web.Models.PhuongPhapDieuTri", b =>
                {
                    b.HasOne("DACS_web.Models.HoSoBenhAn", "HoSoBenhAn")
                        .WithMany("PhuongPhapDieuTris")
                        .HasForeignKey("MaHoSo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoBenhAn");
                });

            modelBuilder.Entity("DACS_web.Models.XetNghiemCLS", b =>
                {
                    b.HasOne("DACS_web.Models.HoSoBenhAn", "HoSoBenhAn")
                        .WithMany()
                        .HasForeignKey("MaHoSo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoBenhAn");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DACS_web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DACS_web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DACS_web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DACS_web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DACS_web.Models.BenhNhan", b =>
                {
                    b.Navigation("CuocHenKhams");

                    b.Navigation("DotKhams");

                    b.Navigation("HoSoBenhAns");
                });

            modelBuilder.Entity("DACS_web.Models.CuocHenKham", b =>
                {
                    b.Navigation("DotKhams");
                });

            modelBuilder.Entity("DACS_web.Models.DonThuoc", b =>
                {
                    b.Navigation("ChiTietDonThuocs");
                });

            modelBuilder.Entity("DACS_web.Models.HoSoBenhAn", b =>
                {
                    b.Navigation("ChanDoans");

                    b.Navigation("HinhAnhYTes");

                    b.Navigation("KetQuaKhamMats");

                    b.Navigation("PhuongPhapDieuTris");
                });

            modelBuilder.Entity("DACS_web.Models.Khoa", b =>
                {
                    b.Navigation("NhanVienYTes");
                });
#pragma warning restore 612, 618
        }
    }
}
